const MATERIAL_SYMBOLS='https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded';
const icon=name=>`${MATERIAL_SYMBOLS}/${name}/default/24px.svg`;
let data=null,selectedDate='',selectedStrategy=null,mode='today',calendarMonth='';
const VIEW_STATE_KEY='strategy-guidance-view';
function savedView(){if(window.__STRATEGY_INITIAL_VIEW__==='history'||window.__STRATEGY_INITIAL_VIEW__==='today')return window.__STRATEGY_INITIAL_VIEW__;try{const value=sessionStorage.getItem(VIEW_STATE_KEY);return value==='history'||value==='today'?value:'today'}catch(_error){return 'today'}}
function saveView(value){if(value!=='history'&&value!=='today')return;try{sessionStorage.setItem(VIEW_STATE_KEY,value)}catch(_error){}}
  const el={list:document.querySelector('#strategy-list'),count:document.querySelector('#strategy-count'),today:document.querySelector('#today-view'),history:document.querySelector('#history-view'),cases:document.querySelector('#cases-view'),search:document.querySelector('#search-view'),input:document.querySelector('#search-input'),searchForm:document.querySelector('#search-form'),context:document.querySelector('.context'),calendarControl:document.querySelector('.calendar-control'),dateTrigger:document.querySelector('#date-calendar-trigger'),dateLabel:document.querySelector('#date-label'),calendar:document.querySelector('#date-calendar'),contextLabel:document.querySelector('#context-label'),contextCount:document.querySelector('#context-count'),toast:document.querySelector('#update-toast'),updatedMessage:document.querySelector('#update-updated'),checkedMessage:document.querySelector('#update-checked')};
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
const doc=key=>data.documents.find(item=>item.dateKey===(key||selectedDate));
const entries=key=>(doc(key)?.entries||[]).filter(item=>!selectedStrategy||item.strategy===selectedStrategy);
const extract=entry=>({manager:entry.cells.find(cell=>(cell.label||cell.sourceLabel||'').includes('投资经理')),cells:entry.cells.filter(cell=>!(cell.label||cell.sourceLabel||'').includes('投资经理'))});
const fieldLabel=cell=>cell.label||cell.sourceLabel||'原文';
const fieldText=cell=>cell.text||cell.value||'';
const viewpointAuthor=value=>{const match=String(value??'').match(/^\s*([\u4e00-\u9fff、，,\s]{2,20})[：:]\s*(?:\r?\n)?/);const candidate=match?match[1].replace(/\s+/g,'').trim():'';return/^[一二三四五六七八九十]、|方面$/.test(candidate)?'':candidate};
const viewpointBody=(value,author)=>author?String(value??'').replace(/^\s*[\u4e00-\u9fff、，,\s]{2,20}[：:]\s*(?:\r?\n)?/,''):fieldText({text:value});
const iconFor=strategy=>/地方债/.test(strategy)?'castle':/REITs/i.test(strategy)?'apartment':/转债/.test(strategy)?'currency_exchange':/宏观/.test(strategy)?'public':/利率债|回转售/.test(strategy)?'diamond':/信用债/.test(strategy)?'text_increase':/ABS/.test(strategy)?'corporate_fare':/海外/.test(strategy)?'directions_boat':/衍生|指数/.test(strategy)?'graph_8':/黄金|商品/.test(strategy)?'account_balance':/基金|资金/.test(strategy)?'savings':/权益|低波/.test(strategy)?'trending_up':'category';
function entryCard(entry){const {manager,cells}=extract(entry);return `<article class="entry"><header><div><span class="entry-kicker">${esc(entry.strategy)}</span><h2>${esc(entry.strategy)}</h2></div><span class="entry-icon"><img src="${icon(iconFor(entry.strategy))}" alt="" /></span></header>${manager?`<div class="entry-manager">投资经理 · ${esc(fieldText(manager))}</div>`:''}${cells.map(cell=>{const text=fieldText(cell),author=viewpointAuthor(text),heading=author||(!manager?fieldLabel(cell):'');return `<section>${heading?`<h3 class="${author?'viewpoint-author':''}">${esc(heading)}</h3>`:''}<p>${esc(viewpointBody(text,author))}</p></section>`}).join('')}</article>`}
function availableStrategies(){if(mode==='cases')return [...new Set((window.__STRATEGY_CASES__||[]).map(item=>item.strategy).filter(Boolean))];const names=new Set((doc()?.entries||[]).map(entry=>entry.strategy));return data.strategies.filter(name=>names.has(name));}
function strategyList(){const values=availableStrategies();el.count.textContent=`${values.length} 项`;el.list.innerHTML=`<button type="button" class="side-button${!selectedStrategy?' is-active':''}" data-strategy=""><img src="${icon('apps')}" alt="" />全部策略</button>${values.map(name=>`<button type="button" class="side-button${selectedStrategy===name?' is-active':''}" data-strategy="${esc(name)}"><img src="${icon(iconFor(name))}" alt="" />${esc(name)}</button>`).join('')}`;el.list.querySelectorAll('[data-strategy]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const keepMode=mode==='history'?'history':mode==='cases'?'cases':'today';selectedStrategy=button.dataset.strategy||null;render(keepMode)}));}
function monthParts(key){const year=2000+Number(key.slice(0,2)),month=Number(key.slice(2,4));return {year,month}}
function shiftMonth(key,delta){const {year,month}=monthParts(key);const date=new Date(year,month-1+delta,1);return `${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}`}
function calendarMarkup(){calendarMonth=calendarMonth||selectedDate.slice(0,4);const {year,month}=monthParts(calendarMonth);const docs=new Map(data.documents.filter(item=>item.dateKey.slice(0,4)===calendarMonth).map(item=>[Number(item.dateKey.slice(4,6)),item]));const first=(new Date(year,month-1,1).getDay()+6)%7;const total=new Date(year,month,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<span class="calendar-blank"></span>';for(let day=1;day<=total;day++){const item=docs.get(day);cells+=item?`<button class="calendar-day has-data ${item.dateKey===selectedDate?'is-active':''}" data-date="${item.dateKey}" aria-label="${item.date}，有策略日表"><span>${day}</span><i></i></button>`:`<button class="calendar-day" disabled aria-label="${year}年${month}月${day}日，无策略日表"><span>${day}</span></button>`}return `<div class="date-calendar-head"><button class="calendar-month-nav" type="button" data-calendar-shift="-1" aria-label="上个月"><img src="${icon('chevron_left')}" alt="" /></button><span><strong>${year} 年 ${month} 月</strong><small>${docs.size} 日已归档</small></span><button class="calendar-month-nav" type="button" data-calendar-shift="1" aria-label="下个月"><img src="${icon('chevron_right')}" alt="" /></button></div><div class="date-calendar-grid"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span>${cells}</div>`}
function renderCalendar(){if(!data)return;el.calendar.innerHTML=calendarMarkup();}
// The date picker deliberately uses the original compact dropdown in every
// view.  It is predictable, does not overlap history content, and leaves the
// long timeline to the page's normal scrollbar.
const inlineHistoryCalendar=()=>false;
function syncCalendarPresentation(){const target=el.context;if(el.calendarControl.parentElement!==target)target.append(el.calendarControl);el.calendarControl.classList.remove('is-inline','is-strategy-history');el.calendarControl.hidden=mode!=='history';el.dateTrigger.hidden=false;el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false')}
function bindDateControl(){el.dateTrigger.addEventListener('click',event=>{event.stopPropagation();el.calendar.hidden=!el.calendar.hidden;el.dateTrigger.setAttribute('aria-expanded',String(!el.calendar.hidden));if(!el.calendar.hidden)renderCalendar()});document.addEventListener('click',event=>{if(!el.calendar.contains(event.target)&&!el.dateTrigger.contains(event.target)){el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false')}})}
function today(){const active=doc();const list=entries();const title=selectedStrategy||'今日策略指引';el.contextLabel.textContent='今日策略';el.contextCount.textContent=`${list.length} 项原文`;el.today.innerHTML=`<header class="hero"><div><p>DAILY STRATEGY GUIDANCE</p><h1>${esc(title)} <time>${esc(active.date)}</time></h1><span>完整保留每条策略的原始指引</span></div><strong>${list.length}<small>项原文</small></strong></header><div class="entry-grid">${list.map(entryCard).join('')||'<p class="empty">此日暂无匹配策略。</p>'}</div>`}
function history(){el.contextLabel.textContent='历史回溯';if(selectedStrategy){const series=data.documents.filter(item=>item.entries.some(entry=>entry.strategy===selectedStrategy));el.contextCount.textContent=`${series.length} 份日表`;el.history.innerHTML=`<header class="page-title page-title-with-calendar"><div><p>HISTORY / TIMELINE</p><h1>${esc(selectedStrategy)} 历史原文</h1><span>${series.length} 份日表</span></div><div id="history-calendar-slot" aria-label="历史日表日历"></div></header><div class="timeline">${series.map(item=>`<article class="timeline-item" data-history-date="${item.dateKey}"><time class="timeline-date">${item.date}</time><div class="entry-grid">${item.entries.filter(entry=>entry.strategy===selectedStrategy).map(entryCard).join('')}</div></article>`).join('')}</div>`;return}const series=data.documents.filter(item=>item.entries.length);el.contextCount.textContent=`${series.length} 日已归档`;el.history.innerHTML=`<header class="page-title page-title-with-calendar"><div><p>HISTORY / BY DATE</p><h1>按日期回溯</h1><span>${series.length} 日已归档</span></div><div id="history-calendar-slot" aria-label="历史日表日历"></div></header><div class="reading"><div class="entry-grid">${entries().map(entryCard).join('')}</div></div>`}
function caseCard(item){const sections=[['背景','background'],['策略判断','judgement'],['执行动作','action'],['结果','result'],['复盘','review']].filter(([,key])=>item[key]);return `<article class="case-card" id="case-${esc(item.id)}"><span class="case-card-icon" style="--icon:url('${icon(iconFor(item.strategy))}')" aria-hidden="true"></span><div class="case-type">${esc(item.strategy)} <span>${esc(item.case_date)}</span></div><h3>${esc(item.title||'未命名案例')}</h3><div class="case-manager">${esc(item.manager)}</div><div class="case-fields">${sections.map(([label,key])=>`<section class="case-field"><div class="label">${label}</div><p>${esc(item[key])}</p></section>`).join('')}</div></article>`}
function renderCases(){if(window.__STRATEGY_CASES__===null){el.contextLabel.textContent='策略案例';el.contextCount.textContent='正在读取';el.cases.innerHTML='<div class="case-loading" role="status"><span class="case-loading-spinner"></span>正在读取案例</div><div class="case-loading-grid" aria-hidden="true"><div></div><div></div></div>';return}const all=window.__STRATEGY_CASES__||[],filtered=all.filter(item=>!selectedStrategy||item.strategy===selectedStrategy),managers=new Set(all.map(item=>String(item.manager||'').trim()).filter(Boolean));el.contextLabel.textContent='策略案例';el.contextCount.textContent=`${filtered.length} 个案例`;const notice=window.__STRATEGY_CASES_ERROR__?`<p class="case-search-unavailable">策略案例暂时无法读取，请稍后刷新重试。</p>`:'';el.cases.innerHTML=`<section class="case-hero"><p class="case-kicker">策略案例库 / MANAGER NOTES</p><h1>萃取、沉淀、迭代、精进</h1><div class="case-meta">这里展示由投资经理填写并发布的实践记录。每日原始策略观点仍以共享表格为准，案例内容是独立的补充档案。</div><div class="case-summary"><span><strong>${all.length}</strong>个案例</span><span><strong>${managers.size}</strong>位撰写者</span></div></section>${notice}<div class="case-grid">${filtered.map(caseCard).join('')||(!notice?'<p class="empty">暂无匹配的已发布案例。</p>':'')}</div>`}
function highlight(value,query){const safe=esc(value);if(!query)return safe;return safe.replace(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi'),'<mark>$1</mark>')}
function search(query){const key=query.trim().toLocaleLowerCase();if(!key){show('today');return}show('search');const hits=[];data.documents.forEach(document=>document.entries.forEach(entry=>entry.cells.forEach(cell=>{const text=`${entry.strategy} ${fieldLabel(cell)} ${fieldText(cell)}`;if(text.toLocaleLowerCase().includes(key))hits.push({document,entry,cell})})));el.search.innerHTML=`<header class="page-title"><p>SEARCH / ORIGINAL TEXT</p><h1>“${esc(query)}”</h1><span>${hits.length} 条原文匹配</span></header><div class="results">${hits.slice(0,100).map((hit,index)=>`<button data-hit="${index}"><small>${hit.document.date} · ${esc(hit.entry.strategy)}</small><strong>${highlight(fieldLabel(hit.cell),query)}</strong><p>${highlight(fieldText(hit.cell),query)}</p></button>`).join('')||'<p class="empty">没有匹配结果。</p>'}</div>`;el.search.querySelectorAll('[data-hit]').forEach(button=>button.addEventListener('click',()=>{const hit=hits[Number(button.dataset.hit)];selectedDate=hit.document.dateKey;selectedStrategy=hit.entry.strategy;calendarMonth=selectedDate.slice(0,4);el.input.value='';show('today');render()}))}
function show(next){mode=next;saveView(next);document.title=`策略指引 · ${{history:'历史回溯',cases:'策略案例',search:'搜索',today:'今日指引'}[next]||'今日指引'}`;['today','history','cases','search'].forEach(name=>{el[name].hidden=name!==next});el.context.hidden=next==='search';document.querySelectorAll('.topbar nav a[href]').forEach(link=>{const active=({today:'/',history:'/archive',cases:'/cases'})[next]===link.getAttribute('href');link.classList.toggle('is-active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current')});document.querySelectorAll('[data-mode]').forEach(button=>button.classList.toggle('is-active',button.dataset.mode===next));if(next==='today')today();if(next==='history')history();if(next==='cases')renderCases();syncCalendarPresentation()}
function render(nextMode=mode){mode=nextMode;strategyList();el.dateLabel.textContent=doc()?.date||'选择日期';renderCalendar();show(nextMode)}
function formatUpdateTime(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return value.replace('T',' ').slice(0,16);return date.toLocaleString('zh-CN',{hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).replace(/\//g,'.')}
  function updateIndicator(state){const checking=Boolean(state?.inProgress),failed=state?.lastResult==='failed',updated=state?.lastResult==='updated',retryCount=Number(state?.retryCount||0),updatedAt=state?.updatedAt?formatUpdateTime(state.updatedAt):'暂无',checkedAt=state?.checkedAt?formatUpdateTime(state.checkedAt):'暂无';el.toast.classList.toggle('is-checking',checking);el.toast.classList.toggle('is-ready',!checking&&!failed);el.toast.classList.toggle('is-failed',failed);el.updatedMessage.textContent=`上次更新：${updatedAt}`;el.checkedMessage.textContent=checking?'上次检查：正在检查':failed?`上次检查：失败${retryCount?`，已重试 ${retryCount} 次`:''}`:`上次检查：${checkedAt}`;el.toast.title=`${el.updatedMessage.textContent}\n${el.checkedMessage.textContent}`}
async function checkUpdate(){if(window.__STRATEGY_UPDATE_STATUS__){updateIndicator(window.__STRATEGY_UPDATE_STATUS__);return}try{const response=await fetch('/api/update-status',{cache:'no-store'});if(!response.ok)throw new Error('status unavailable');updateIndicator(await response.json())}catch(_error){updateIndicator({inProgress:false,lastResult:'',updatedAt:''})}}
function start(payload){data=payload;selectedDate=data.documents[0]?.dateKey||'';calendarMonth=selectedDate.slice(0,4);const initialMode=savedView();el.input.addEventListener('input',event=>search(event.target.value));el.searchForm.addEventListener('submit',event=>{event.preventDefault();search(el.input.value)});document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();show(button.dataset.mode)}));document.querySelector('.brand')?.addEventListener('click',()=>saveView('today'));document.addEventListener('click',event=>{const monthButton=event.target.closest('[data-calendar-shift]');if(monthButton){event.preventDefault();event.stopImmediatePropagation();calendarMonth=shiftMonth(calendarMonth,Number(monthButton.dataset.calendarShift));renderCalendar();return}const dateButton=event.target.closest('[data-date]');if(!dateButton)return;event.preventDefault();const keepStrategy=mode==='history'&&Boolean(selectedStrategy);selectedDate=dateButton.dataset.date;if(!keepStrategy)selectedStrategy=null;calendarMonth=selectedDate.slice(0,4);el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false');render();if(keepStrategy)requestAnimationFrame(()=>document.querySelector(`[data-history-date="${selectedDate}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}))});bindDateControl();render(initialMode);checkUpdate();if(!window.__STRATEGY_UPDATE_STATUS__)window.setInterval(checkUpdate,3000)}
const source=window.__STRATEGY_DATA__?Promise.resolve(window.__STRATEGY_DATA__):fetch('../site/site-data.json').then(response=>response.json());source.then(start).catch(error=>{el.today.textContent=`无法读取展示数据：${error.message}`});
// Case data is a separate editorial layer. Only published records reach this frame.
const strategyOriginalSearch=search;
search=function(query){
  strategyOriginalSearch(query);
  const key=query.trim().toLocaleLowerCase();
  if(!key)return;
  const cases=(window.__STRATEGY_CASES__||[]).filter(item=>[item.title,item.strategy,item.manager,item.background,item.judgement,item.action,item.result,item.review].some(value=>String(value||'').toLocaleLowerCase().includes(key)));
  if(!cases.length){
    if(window.__STRATEGY_CASES_ERROR__){const note=document.createElement('p');note.className='case-search-unavailable';note.textContent=`策略案例暂不可搜索：${window.__STRATEGY_CASES_ERROR__}`;el.search.querySelector('.results').after(note)}
    return;
  }
  const results=el.search.querySelector('.results');
  const noOriginal=results.querySelector('.empty');
  if(noOriginal)noOriginal.textContent='原始观点无匹配；下方有策略案例。';
  const section=document.createElement('section');section.className='case-search-group';
  section.innerHTML=`<h2>策略案例 <small>${cases.length} 条已发布匹配</small></h2>${cases.slice(0,50).map(item=>`<a class="case-search-hit" href="/cases?case=${encodeURIComponent(item.id)}"><small>${esc(item.case_date)} · ${esc(item.strategy)} · ${esc(item.manager)}</small><strong>${highlight(item.title,query)}</strong><p>${highlight([item.background,item.judgement,item.action,item.result,item.review].find(value=>String(value||'').toLocaleLowerCase().includes(key))||item.judgement,query)}</p></a>`).join('')}`;
  results.after(section);
  el.search.querySelector('.page-title span').textContent+=` · ${cases.length} 条案例匹配`;
};
document.querySelector('.brand')?.addEventListener('click',event=>{event.preventDefault();selectedStrategy=null;if(data)render('today')});
source.then(()=>{if(window.__STRATEGY_SEARCH_QUERY__){el.input.value=window.__STRATEGY_SEARCH_QUERY__;search(el.input.value)}});
// Keep the public shell mounted: route changes alter only the content view.
let requestedRoute=null;
function applyRoute(route){if(!route||!data){requestedRoute=route;return}requestedRoute=null;const next=['today','history','cases'].includes(route.view)?route.view:'today';const focused=String(route.case||'');if(next!==mode){selectedStrategy=null;render(next)}if(next==='cases'&&focused){const focusedCase=(window.__STRATEGY_CASES__||[]).find(item=>String(item.id)===focused);if(focusedCase&&selectedStrategy&&selectedStrategy!==focusedCase.strategy){selectedStrategy=null;render('cases')}requestAnimationFrame(()=>document.getElementById(`case-${focused}`)?.scrollIntoView({behavior:'smooth',block:'center'}))}if(route.q){el.input.value=route.q;search(route.q)}}
window.addEventListener('message',event=>{if(event.source!==window.parent||event.data?.type!=='strategy:route')return;applyRoute(event.data.route)});
window.addEventListener('message',event=>{if(event.source!==window.parent||event.data?.type!=='strategy:data')return;const payload=event.data.payload||{};const previous=JSON.stringify([window.__STRATEGY_CASES__,window.__STRATEGY_CASES_ERROR__]);window.__STRATEGY_CASES__=Array.isArray(payload.cases)?payload.cases:[];window.__STRATEGY_CASES_ERROR__=payload.error||'';window.__STRATEGY_UPDATE_STATUS__=payload.status||{};updateIndicator(window.__STRATEGY_UPDATE_STATUS__);if(previous!==JSON.stringify([window.__STRATEGY_CASES__,window.__STRATEGY_CASES_ERROR__])){source.then(()=>{if(mode==='cases'){strategyList();renderCases()}else if(mode==='search'&&el.input.value)search(el.input.value)})}});
source.then(()=>{if(requestedRoute)applyRoute(requestedRoute)});
document.addEventListener('click',event=>{if(!window.__STRATEGY_DATA__)return;const link=event.target.closest('.topbar a[href], .case-search-hit[href]');if(!link||link.target==='_blank')return;const path=link.getAttribute('href');const destination={"/":"today","/archive":"history","/cases":"cases"}[path?.split('?')[0]];if(!destination)return;event.preventDefault();event.stopImmediatePropagation();if(destination!==mode){selectedStrategy=null;render(destination)}const focused=path?.startsWith('/cases?')?new URLSearchParams(path.split('?')[1]).get('case'):'';if(focused)applyRoute({view:'cases',case:focused});window.parent.postMessage({type:'strategy:navigate',path},'*')},true);
