const MATERIAL_SYMBOLS='https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded';
const icon=name=>`${MATERIAL_SYMBOLS}/${name}/default/24px.svg`;
let data=null,selectedDate='',selectedStrategy=null,mode='today',calendarMonth='';
const el={list:document.querySelector('#strategy-list'),count:document.querySelector('#strategy-count'),today:document.querySelector('#today-view'),history:document.querySelector('#history-view'),search:document.querySelector('#search-view'),input:document.querySelector('#search-input'),searchForm:document.querySelector('#search-form'),context:document.querySelector('.context'),calendarControl:document.querySelector('.calendar-control'),dateTrigger:document.querySelector('#date-calendar-trigger'),dateLabel:document.querySelector('#date-label'),calendar:document.querySelector('#date-calendar'),contextLabel:document.querySelector('#context-label'),contextCount:document.querySelector('#context-count'),toast:document.querySelector('#update-toast'),toastMessage:document.querySelector('#update-message')};
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
const doc=key=>data.documents.find(item=>item.dateKey===(key||selectedDate));
const entries=key=>(doc(key)?.entries||[]).filter(item=>!selectedStrategy||item.strategy===selectedStrategy);
const extract=entry=>({manager:entry.cells.find(cell=>(cell.label||cell.sourceLabel||'').includes('投资经理')),cells:entry.cells.filter(cell=>!(cell.label||cell.sourceLabel||'').includes('投资经理'))});
const fieldLabel=cell=>cell.label||cell.sourceLabel||'原文';
const fieldText=cell=>cell.text||cell.value||'';
const viewpointAuthor=value=>{const match=String(value??'').match(/^\s*([\u4e00-\u9fff、，,\s]{2,20})[：:]\s*(?:\r?\n)?/);const candidate=match?match[1].replace(/\s+/g,'').trim():'';return/^[一二三四五六七八九十]、|方面$/.test(candidate)?'':candidate};
const viewpointBody=(value,author)=>author?String(value??'').replace(/^\s*[\u4e00-\u9fff、，,\s]{2,20}[：:]\s*(?:\r?\n)?/,''):fieldText({text:value});
const iconFor=strategy=>/地方债/.test(strategy)?'castle':/REITs/i.test(strategy)?'apartment':/转债/.test(strategy)?'currency_exchange':/宏观/.test(strategy)?'public':/利率债|回转售/.test(strategy)?'diamond':/信用债/.test(strategy)?'text_increase':/ABS/.test(strategy)?'corporate_fare':/海外/.test(strategy)?'directions_boat':/衍生|指数/.test(strategy)?'graph_8':/黄金|商品/.test(strategy)?'account_balance':/基金|资金/.test(strategy)?'savings':/权益|低波/.test(strategy)?'trending_up':'category';
function entryCard(entry){const {manager,cells}=extract(entry);return `<article class="entry"><header><div><span class="entry-kicker">${esc(entry.strategy)}</span><h2>${esc(entry.strategy)}</h2></div><span class="entry-icon"><img src="${icon(iconFor(entry.strategy))}" alt="" /></span></header>${manager?`<div class="entry-manager">投资经理 · ${esc(fieldText(manager))}</div>`:''}${cells.map(cell=>{const text=fieldText(cell),author=viewpointAuthor(text),heading=author||(!manager?fieldLabel(cell):'');return `<section>${heading?`<h3 class="${author?'viewpoint-author':''}">${esc(heading)}</h3>`:''}<p>${esc(viewpointBody(text,author))}</p></section>`}).join('')}</article>`}
function availableStrategies(){const names=new Set((doc()?.entries||[]).map(entry=>entry.strategy));return data.strategies.filter(name=>names.has(name));}
function strategyList(){const values=availableStrategies();el.count.textContent=`${values.length} 项`;el.list.innerHTML=`<button class="side-button${!selectedStrategy?' is-active':''}" data-strategy=""><img src="${icon('apps')}" alt="" />全部策略</button>${values.map(name=>`<button class="side-button${selectedStrategy===name?' is-active':''}" data-strategy="${esc(name)}"><img src="${icon(iconFor(name))}" alt="" />${esc(name)}</button>`).join('')}`;el.list.querySelectorAll('[data-strategy]').forEach(button=>button.addEventListener('click',()=>{selectedStrategy=button.dataset.strategy||null;render()}));}
function monthParts(key){const year=2000+Number(key.slice(0,2)),month=Number(key.slice(2,4));return {year,month}}
function shiftMonth(key,delta){const {year,month}=monthParts(key);const date=new Date(year,month-1+delta,1);return `${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}`}
function calendarMarkup(){calendarMonth=calendarMonth||selectedDate.slice(0,4);const {year,month}=monthParts(calendarMonth);const docs=new Map(data.documents.filter(item=>item.dateKey.slice(0,4)===calendarMonth).map(item=>[Number(item.dateKey.slice(4,6)),item]));const first=(new Date(year,month-1,1).getDay()+6)%7;const total=new Date(year,month,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<span class="calendar-blank"></span>';for(let day=1;day<=total;day++){const item=docs.get(day);cells+=item?`<button class="calendar-day has-data ${item.dateKey===selectedDate?'is-active':''}" data-date="${item.dateKey}" aria-label="${item.date}，有策略日表"><span>${day}</span><i></i></button>`:`<button class="calendar-day" disabled aria-label="${year}年${month}月${day}日，无策略日表"><span>${day}</span></button>`}return `<div class="date-calendar-head"><button class="calendar-month-nav" type="button" data-calendar-shift="-1" aria-label="上个月"><img src="${icon('chevron_left')}" alt="" /></button><span><strong>${year} 年 ${month} 月</strong><small>${docs.size} 日已归档</small></span><button class="calendar-month-nav" type="button" data-calendar-shift="1" aria-label="下个月"><img src="${icon('chevron_right')}" alt="" /></button></div><div class="date-calendar-grid"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span>${cells}</div>`}
function renderCalendar(){if(!data)return;el.calendar.innerHTML=calendarMarkup();}
const inlineHistoryCalendar=()=>mode==='history';
function syncCalendarPresentation(){const inline=inlineHistoryCalendar(),target=el.context;if(el.calendarControl.parentElement!==target)target.append(el.calendarControl);el.calendarControl.classList.toggle('is-inline',inline);el.calendarControl.classList.toggle('is-strategy-history',inline);el.dateTrigger.hidden=inline;if(inline){el.calendar.hidden=false;el.dateTrigger.setAttribute('aria-expanded','false');renderCalendar()}else{el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false')}}
function bindDateControl(){el.dateTrigger.addEventListener('click',event=>{event.stopPropagation();el.calendar.hidden=!el.calendar.hidden;el.dateTrigger.setAttribute('aria-expanded',String(!el.calendar.hidden));if(!el.calendar.hidden)renderCalendar()});document.addEventListener('click',event=>{if(!inlineHistoryCalendar()&&!el.calendar.contains(event.target)&&!el.dateTrigger.contains(event.target)){el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false')}})}
function today(){const active=doc();const list=entries();const title=selectedStrategy||'今日策略指引';el.contextLabel.textContent='今日策略';el.contextCount.textContent=`${list.length} 项原文`;el.today.innerHTML=`<header class="hero"><div><p>DAILY STRATEGY GUIDANCE</p><h1>${esc(title)} <time>${esc(active.date)}</time></h1><span>完整保留每条策略的原始指引</span></div><strong>${list.length}<small>项原文</small></strong></header><div class="entry-grid">${list.map(entryCard).join('')||'<p class="empty">此日暂无匹配策略。</p>'}</div>`}
function history(){el.contextLabel.textContent='历史回溯';if(selectedStrategy){const series=data.documents.filter(item=>item.entries.some(entry=>entry.strategy===selectedStrategy));el.contextCount.textContent=`${series.length} 份日表`;el.history.innerHTML=`<header class="page-title page-title-with-calendar"><div><p>HISTORY / TIMELINE</p><h1>${esc(selectedStrategy)} 历史原文</h1><span>${series.length} 份日表</span></div><div id="history-calendar-slot" aria-label="历史日表日历"></div></header><div class="timeline">${series.map(item=>`<article class="timeline-item" data-history-date="${item.dateKey}"><time class="timeline-date">${item.date}</time><div class="entry-grid">${item.entries.filter(entry=>entry.strategy===selectedStrategy).map(entryCard).join('')}</div></article>`).join('')}</div>`;return}const series=data.documents.filter(item=>item.entries.length);el.contextCount.textContent=`${series.length} 日已归档`;el.history.innerHTML=`<header class="page-title page-title-with-calendar"><div><p>HISTORY / BY DATE</p><h1>按日期回溯</h1><span>${series.length} 日已归档</span></div><div id="history-calendar-slot" aria-label="历史日表日历"></div></header><div class="reading"><div class="entry-grid">${entries().map(entryCard).join('')}</div></div>`}
function highlight(value,query){const safe=esc(value);if(!query)return safe;return safe.replace(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi'),'<mark>$1</mark>')}
function search(query){const key=query.trim().toLocaleLowerCase();if(!key){show('today');return}show('search');const hits=[];data.documents.forEach(document=>document.entries.forEach(entry=>entry.cells.forEach(cell=>{const text=`${entry.strategy} ${fieldLabel(cell)} ${fieldText(cell)}`;if(text.toLocaleLowerCase().includes(key))hits.push({document,entry,cell})})));el.search.innerHTML=`<header class="page-title"><p>SEARCH / ORIGINAL TEXT</p><h1>“${esc(query)}”</h1><span>${hits.length} 条原文匹配</span></header><div class="results">${hits.slice(0,100).map((hit,index)=>`<button data-hit="${index}"><small>${hit.document.date} · ${esc(hit.entry.strategy)}</small><strong>${highlight(fieldLabel(hit.cell),query)}</strong><p>${highlight(fieldText(hit.cell),query)}</p></button>`).join('')||'<p class="empty">没有匹配结果。</p>'}</div>`;el.search.querySelectorAll('[data-hit]').forEach(button=>button.addEventListener('click',()=>{const hit=hits[Number(button.dataset.hit)];selectedDate=hit.document.dateKey;selectedStrategy=hit.entry.strategy;calendarMonth=selectedDate.slice(0,4);el.input.value='';show('today');render()}))}
function show(next){mode=next;['today','history','search'].forEach(name=>{el[name].hidden=name!==next});el.context.hidden=next==='search';document.querySelectorAll('[data-mode]').forEach(button=>button.classList.toggle('is-active',button.dataset.mode===next));if(next==='today')today();if(next==='history')history();syncCalendarPresentation()}
function render(){strategyList();el.dateLabel.textContent=doc()?.date||'选择日期';renderCalendar();show(mode)}
function formatUpdateTime(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return value.replace('T',' ').slice(0,16);return date.toLocaleString('zh-CN',{hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).replace(/\//g,'.')}
function updateIndicator(state){const checking=Boolean(state?.inProgress),failed=state?.lastResult==='failed',updated=state?.lastResult==='updated',result=checking?'正在检查策略日表':failed?'日表更新失败，将自动重试':updated?'日表已更新':'日表检查完成',time=state?.updatedAt?`${updated?'上次更新':'上次检查'} ${formatUpdateTime(state.updatedAt)}`:'';el.toast.classList.toggle('is-checking',checking);el.toast.classList.toggle('is-ready',!checking&&!failed);el.toast.classList.toggle('is-failed',failed);el.toastMessage.textContent=time?`${result} · ${time}`:result;el.toast.title=el.toastMessage.textContent}
async function checkUpdate(){if(window.__STRATEGY_UPDATE_STATUS__){updateIndicator(window.__STRATEGY_UPDATE_STATUS__);return}try{const response=await fetch('/api/update-status',{cache:'no-store'});if(!response.ok)throw new Error('status unavailable');updateIndicator(await response.json())}catch(_error){updateIndicator({inProgress:false,lastResult:'',updatedAt:''})}}
function start(payload){data=payload;selectedDate=data.documents[0]?.dateKey||'';calendarMonth=selectedDate.slice(0,4);el.input.addEventListener('input',event=>search(event.target.value));el.searchForm.addEventListener('submit',event=>{event.preventDefault();search(el.input.value)});document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.mode)));document.addEventListener('click',event=>{const monthButton=event.target.closest('[data-calendar-shift]');if(monthButton){event.preventDefault();event.stopImmediatePropagation();calendarMonth=shiftMonth(calendarMonth,Number(monthButton.dataset.calendarShift));renderCalendar();return}const dateButton=event.target.closest('[data-date]');if(!dateButton)return;event.preventDefault();const wasInline=inlineHistoryCalendar(),keepStrategy=wasInline&&mode==='history'&&Boolean(selectedStrategy);selectedDate=dateButton.dataset.date;if(!keepStrategy)selectedStrategy=null;calendarMonth=selectedDate.slice(0,4);if(!wasInline){el.calendar.hidden=true;el.dateTrigger.setAttribute('aria-expanded','false')}render();if(keepStrategy)requestAnimationFrame(()=>document.querySelector(`[data-history-date="${selectedDate}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}))});bindDateControl();render();checkUpdate();if(!window.__STRATEGY_UPDATE_STATUS__)window.setInterval(checkUpdate,3000)}
const source=window.__STRATEGY_DATA__?Promise.resolve(window.__STRATEGY_DATA__):fetch('../site/site-data.json').then(response=>response.json());source.then(start).catch(error=>{el.today.textContent=`无法读取展示数据：${error.message}`});
