let data, selectedDate, selectedStrategy = null, mode = 'today';
const el = { list: document.querySelector('#strategy-list'), count: document.querySelector('#strategy-count'), select: document.querySelector('#date-select'), today: document.querySelector('#today-view'), history: document.querySelector('#history-view'), compare: document.querySelector('#compare-view'), search: document.querySelector('#search-view'), input: document.querySelector('#search-input') };
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;' }[char]));
const doc = key => data.documents.find(item => item.dateKey === (key || selectedDate));
const entries = key => (doc(key)?.entries || []).filter(item => !selectedStrategy || item.strategy === selectedStrategy);
const extract = entry => ({ manager: entry.cells.find(cell => cell.label.includes('投资经理')), cells: entry.cells.filter(cell => !cell.label.includes('投资经理')) });
function entryCard(entry) { const { manager, cells } = extract(entry); return `<article class="entry"><header><div><span class="entry-kicker">原始策略指引</span><h2>${esc(entry.strategy)}</h2></div><small>原表第 ${entry.row} 行</small></header>${cells.map(cell => `<section><h3>${esc(cell.label)}</h3><p>${esc(cell.text)}</p></section>`).join('')}${manager ? `<footer>投资经理：${esc(manager.text)}</footer>` : ''}</article>`; }
function strategyList() { const available = new Set((doc()?.entries || []).map(entry => entry.strategy)); if (selectedStrategy && !available.has(selectedStrategy)) selectedStrategy = null; const values = data.strategies.filter(name => available.has(name)); el.count.textContent = `${values.length} 项`; el.list.innerHTML = `<button class="side-button${!selectedStrategy?' is-active':''}" data-strategy="">全部策略</button>${values.map(name => `<button class="side-button${selectedStrategy===name?' is-active':''}" data-strategy="${esc(name)}">${esc(name)}</button>`).join('')}`; el.list.querySelectorAll('[data-strategy]').forEach(button => button.addEventListener('click', () => { selectedStrategy = button.dataset.strategy || null; render(); })); }
function today() { const active = doc(); const list = entries(); el.today.innerHTML = `<header class="hero"><div><p>${active.date.replaceAll('.',' / ')} · DAILY STRATEGY GUIDANCE</p><h1>${selectedStrategy || '最新策略指引'}</h1><span>完整保留每条策略的原始指引</span></div><strong>${list.length}<small>项原文</small></strong></header><div class="entry-grid">${list.map(entryCard).join('') || '<p class="empty">此日暂无匹配策略。</p>'}</div>`; }
function history() { const docs = data.documents.filter(item => item.entries.some(entry => !selectedStrategy || entry.strategy === selectedStrategy)); el.history.innerHTML = `<header class="page-title"><p>HISTORY</p><h1>${selectedStrategy ? `${esc(selectedStrategy)} 历史原文` : '按日期回溯'}</h1></header><div class="history-layout"><div class="dates">${docs.map(item => `<button data-history="${item.dateKey}" class="${item.dateKey===selectedDate?'is-active':''}">${item.date}</button>`).join('')}</div><div class="reading">${entries().map(entryCard).join('')}</div></div>`; el.history.querySelectorAll('[data-history]').forEach(button => button.addEventListener('click', () => { selectedDate = button.dataset.history; el.select.value = selectedDate; render(); })); }
function compare() { const docs = data.documents.filter(item => item.entries.some(entry => !selectedStrategy || entry.strategy === selectedStrategy)); const first = docs[0], second = docs[1] || docs[0]; el.compare.innerHTML = `<header class="page-title"><p>SIDE BY SIDE</p><h1>${selectedStrategy ? `${esc(selectedStrategy)} 原文对照` : '原文对照'}</h1></header><div class="compare-select"><label>左侧 <select id="left">${docs.map(item => `<option value="${item.dateKey}">${item.date}</option>`).join('')}</select></label><label>右侧 <select id="right">${docs.map(item => `<option value="${item.dateKey}" ${item.dateKey===second.dateKey?'selected':''}>${item.date}</option>`).join('')}</select></label></div><div id="compare-output"></div>`; const draw = () => { const dates = [el.compare.querySelector('#left').value, el.compare.querySelector('#right').value]; el.compare.querySelector('#compare-output').innerHTML = `<div class="compare-grid">${dates.map(key => `<div><p class="compare-date">${doc(key).date}</p>${entries(key).map(entryCard).join('') || '<p class="empty">没有匹配内容。</p>'}</div>`).join('')}</div>`; }; el.compare.querySelectorAll('select').forEach(select => select.addEventListener('change', draw)); draw(); }
function search(query) { const key = query.trim().toLocaleLowerCase(); if (!key) { show('today'); return; } const hits = []; data.documents.forEach(document => document.entries.forEach(entry => entry.cells.forEach(cell => { if (`${entry.strategy} ${cell.label} ${cell.text}`.toLocaleLowerCase().includes(key)) hits.push({ document, entry, cell }); }))); el.search.innerHTML = `<header class="page-title"><p>SEARCH</p><h1>“${esc(query)}”</h1><span>${hits.length} 条原文匹配</span></header><div class="results">${hits.slice(0,80).map((hit,index) => `<button data-hit="${index}"><small>${hit.document.date} · ${esc(hit.entry.strategy)}</small><strong>${esc(hit.cell.label)}</strong><p>${esc(hit.cell.text)}</p></button>`).join('') || '<p class="empty">没有匹配结果。</p>'}</div>`; el.search.querySelectorAll('[data-hit]').forEach(button => button.addEventListener('click', () => { const hit=hits[Number(button.dataset.hit)]; selectedDate=hit.document.dateKey; selectedStrategy=hit.entry.strategy; el.select.value=selectedDate; el.input.value=''; show('today'); })); }
function show(next) { mode=next; ['today','history','compare','search'].forEach(name => { el[name].hidden=name!==next; }); document.querySelectorAll('[data-mode]').forEach(button => button.classList.toggle('is-active',button.dataset.mode===next)); if(next==='today') today(); if(next==='history') history(); if(next==='compare') compare(); }
function render() { strategyList(); show(mode); }
fetch('../site/site-data.json').then(response => response.json()).then(payload => { data=payload; selectedDate=data.documents[0].dateKey; el.select.innerHTML=data.documents.map(item => `<option value="${item.dateKey}">${item.date}</option>`).join(''); el.select.addEventListener('change', () => { selectedDate=el.select.value; render(); }); document.querySelectorAll('[data-mode]').forEach(button => button.addEventListener('click',()=>show(button.dataset.mode))); el.input.addEventListener('input',event=>search(event.target.value)); render(); }).catch(error => { el.today.textContent=`无法读取展示数据：${error.message}`; });
